"use client";

import { useState, useCallback } from "react";
import { motion } from "framer-motion";
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend,
} from "recharts";
import { jsPDF } from "jspdf";
import type { Evaluation, PathResult } from "../lib/types";

interface Props {
  evaluation: Evaluation;
  onBack: () => void;
}

const fmt = (n: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);
const fmtShort = (n: number) => {
  if (Math.abs(n) >= 10000000) return `₹${(n / 10000000).toFixed(2)}Cr`;
  if (Math.abs(n) >= 100000) return `₹${(n / 100000).toFixed(1)}L`;
  return fmt(n);
};
const ym = (m: number) => `${Math.floor(m / 12)}y ${m % 12}m`;

const colors: Record<string, string> = { prepay: "#059669", invest: "#2563eb", balanced: "#7c3aed" };

function toLakhs(n: number) { return `₹${(n / 100000).toFixed(1)}L`; }

function usePdfExport(evaluation: Evaluation) {
  const [exporting, setExporting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const handleExport = useCallback(() => {
    setError(null);
    setExporting(true);
    try {
      const { inputs, paths, winner } = evaluation;
      const pdf = new jsPDF("p", "mm", "a4");
      const pw = pdf.internal.pageSize.getWidth();
      const ph = pdf.internal.pageSize.getHeight();
      const margin = 20;
      let y = margin;

      function addLine() { y += 1; pdf.setDrawColor(200); pdf.line(margin, y, pw - margin, y); y += 4; }

      function text(t: string, size = 10, style: "normal" | "bold" = "normal") {
        pdf.setFont("helvetica", style);
        pdf.setFontSize(size);
        pdf.text(t, margin, y);
        y += size * 0.45;
      }

      function kv(label: string, val: string, size = 9) {
        pdf.setFont("helvetica", "normal"); pdf.setFontSize(size);
        const lw = pdf.getTextWidth(label + "  ");
        pdf.text(label, margin, y);
        pdf.setFont("helvetica", "bold");
        pdf.text(val, margin + lw, y);
        y += size * 0.45;
      }

      function checkPage() { if (y > ph - margin) { pdf.addPage(); y = margin + 10; } }

      const FMT = (n: number) => "₹" + Math.abs(n).toLocaleString("en-IN", { maximumFractionDigits: 0 });
      const YM = (m: number) => `${Math.floor(m / 12)}y ${m % 12}m`;

      // Title
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(18);
      pdf.setTextColor(30);
      pdf.text("Decide — Prepay vs Invest Report", margin, y); y += 10;
      pdf.setFont("helvetica", "normal"); pdf.setFontSize(8);
      pdf.setTextColor(150);
      pdf.text("Generated by Decide.app | " + new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" }), margin, y);
      y += 8;
      addLine();

      // Your Loan
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(12); pdf.setTextColor(30);
      text("Loan Details", 12, "bold");
      pdf.setFont("helvetica", "normal"); pdf.setFontSize(9); pdf.setTextColor(80);
      kv("Loan Amount", FMT(inputs.principal));
      kv("Interest Rate", `${inputs.annualRate}%`);
      kv("Tenure", `${inputs.tenureYears} years`);
      kv("Monthly Surplus", FMT(inputs.monthlySurplus));
      kv("Yearly Surplus", FMT(inputs.yearlySurplus));
      kv("One-time Surplus", FMT(inputs.lumpSum));
      kv("Expected Return", `${inputs.expectedReturnRate}%`);
      kv("Inflation", `${inputs.inflationRate}%`);
      kv("Tax Bracket", `${inputs.taxRate}%`);
      y += 2;
      addLine();

      // Recommendation
      checkPage();
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(14); pdf.setTextColor(5, 150, 105);
      text("Our Recommendation: " + winner.label, 14, "bold");
      pdf.setFont("helvetica", "normal"); pdf.setFontSize(9); pdf.setTextColor(60);
      text(winner.description, 9);
      y += 2;
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(10); pdf.setTextColor(30);
      kv("Payoff Time", YM(winner.payoffMonths));
      kv("Total Interest Paid", FMT(winner.totalInterest));
      kv("Interest Saved", FMT(winner.interestSaved));
      kv("Investment Value", FMT(winner.investmentValue));
      kv("Net Worth", FMT(winner.netWorth));
      kv("Net Benefit (post-tax)", FMT(winner.totalBenefit));
      y += 2;
      addLine();

      // Comparison table
      checkPage();
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(12); pdf.setTextColor(30);
      text("Strategy Comparison", 12, "bold");
      y += 1;

      const cols = ["Strategy", "Payoff", "Interest", "Investment", "Tax Saved", "Net Worth"];
      const colW = (pw - 2 * margin) / cols.length;
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); pdf.setTextColor(100);
      let cx = margin;
      cols.forEach(c => { pdf.text(c, cx, y, { align: c === "Strategy" ? "left" : "center" }); cx += colW; });
      y += 4;

      paths.forEach((p, i) => {
        checkPage();
        pdf.setFont("helvetica", i === 0 ? "bold" : "normal"); pdf.setFontSize(8);
        pdf.setTextColor(i === 0 ? 5 : 60, i === 0 ? 150 : 60, i === 0 ? 105 : 60);
        cx = margin;
        pdf.text(p.label, cx, y); cx += colW;
        pdf.text(YM(p.payoffMonths), cx, y, { align: "center" }); cx += colW;
        pdf.text(FMT(p.totalInterest), cx, y, { align: "center" }); cx += colW;
        pdf.text(p.investmentValue > 0 ? FMT(p.investmentValue) : "—", cx, y, { align: "center" }); cx += colW;
        pdf.text(FMT(p.taxBreakdown.totalTaxSaved), cx, y, { align: "center" }); cx += colW;
        pdf.text(FMT(p.netWorth), cx, y, { align: "center" }); cx += colW;
        y += 4;
      });
      y += 2;
      addLine();

      // Tax Breakdown
      checkPage();
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(12); pdf.setTextColor(30);
      text("Tax Impact (at " + inputs.taxRate + "% bracket)", 12, "bold");
      pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); pdf.setTextColor(100);
      text("Section 24: Up to ₹2L/yr interest deductible. Section 80C: Up to ₹1.5L/yr principal deductible. LTCG: 10% on gains > ₹1L.", 8);
      y += 1;

      const tCols = ["Strategy", "Sec 24 Saved", "Sec 80C Saved", "LTCG Tax", "Post-Tax Benefit"];
      const tColW = (pw - 2 * margin) / tCols.length;
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); pdf.setTextColor(100);
      cx = margin;
      tCols.forEach(c => { pdf.text(c, cx, y, { align: c === "Strategy" ? "left" : "center" }); cx += tColW; });
      y += 4;

      paths.forEach((p, i) => {
        checkPage();
        pdf.setFont("helvetica", i === 0 ? "bold" : "normal"); pdf.setFontSize(8);
        pdf.setTextColor(i === 0 ? 5 : 60, i === 0 ? 150 : 60, i === 0 ? 105 : 60);
        cx = margin;
        pdf.text(p.label, cx, y); cx += tColW;
        pdf.text(FMT(p.taxBreakdown.section24Savings), cx, y, { align: "center" }); cx += tColW;
        pdf.text(FMT(p.taxBreakdown.section80CSavings), cx, y, { align: "center" }); cx += tColW;
        pdf.text(p.taxBreakdown.ltcgTax > 0 ? FMT(p.taxBreakdown.ltcgTax) : "—", cx, y, { align: "center" }); cx += tColW;
        pdf.text(FMT(p.totalBenefit), cx, y, { align: "center" }); cx += tColW;
        y += 4;
      });
      y += 2;
      addLine();

      // Inflation
      checkPage();
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(12); pdf.setTextColor(30);
      text("Inflation Reality Check (" + inputs.inflationRate + "% inflation)", 12, "bold");
      y += 1;
      const iCols = ["Strategy", "Nominal Net Worth", "Real Net Worth", "Loss to Inflation"];
      const iColW = (pw - 2 * margin) / iCols.length;
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); pdf.setTextColor(100);
      cx = margin;
      iCols.forEach(c => { pdf.text(c, cx, y, { align: c === "Strategy" ? "left" : "center" }); cx += iColW; });
      y += 4;
      paths.forEach((p, i) => {
        checkPage();
        pdf.setFont("helvetica", i === 0 ? "bold" : "normal"); pdf.setFontSize(8);
        pdf.setTextColor(i === 0 ? 5 : 60, i === 0 ? 150 : 60, i === 0 ? 105 : 60);
        cx = margin;
        pdf.text(p.label, cx, y); cx += iColW;
        pdf.text(FMT(p.netWorth), cx, y, { align: "center" }); cx += iColW;
        pdf.text(FMT(p.netWorthReal), cx, y, { align: "center" }); cx += iColW;
        pdf.text(FMT(p.netWorth - p.netWorthReal), cx, y, { align: "center" }); cx += iColW;
        y += 4;
      });
      y += 2;
      addLine();

      // What-If
      checkPage();
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(12); pdf.setTextColor(30);
      text("What-If Scenarios", 12, "bold");
      y += 1;
      evaluation.whatIfScenarios.forEach((s) => {
        checkPage();
        pdf.setFont("helvetica", "bold"); pdf.setFontSize(9); pdf.setTextColor(30);
        text(s.label + " (" + s.multiplier + "x surplus) → " + s.evaluation.winner.label, 9, "bold");
        pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); pdf.setTextColor(80);
        kv("  Payoff", YM(s.evaluation.winner.payoffMonths));
        kv("  Net Worth", FMT(s.evaluation.winner.netWorth));
        kv("  Benefit", FMT(s.evaluation.winner.totalBenefit));
        y += 1;
      });
      y += 2;

      // Footer
      checkPage();
      addLine();
      pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); pdf.setTextColor(150);
      text("Not financial advice. This is for educational purposes only. Consult a SEBI-registered advisor.", 8);
      text("Decide.app — prepay vs invest calculator", 8);

      pdf.save("Decide-Report.pdf");
    } catch (err) {
      console.error("PDF export failed:", err);
      setError("Could not generate PDF. Try again.");
    } finally {
      setExporting(false);
    }
  }, [evaluation]);
  return { handleExport, exporting, error, clearError: () => setError(null) };
}

function VerdictCard({ winner, inputs }: { winner: PathResult; inputs: Evaluation["inputs"] }) {
  const totalSaved = winner.interestSaved + winner.investmentValue;
  const postTaxTotal = winner.totalBenefit;
  return (
    <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ delay: 0.1, type: "spring", stiffness: 120 }}
      className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 p-6 sm:p-8 text-white shadow-2xl"
    >
      <div className="absolute top-0 right-0 w-72 h-72 bg-emerald-500/5 rounded-full -translate-y-1/3 translate-x-1/4" />
      <div className="absolute bottom-0 left-0 w-48 h-48 bg-blue-500/5 rounded-full translate-y-1/3 -translate-x-1/4" />
      <div className="relative">
        <div className="flex items-center gap-3 mb-5">
          <span className="text-3xl">{winner.emoji}</span>
          <div>
            <p className="text-emerald-300 text-xs font-bold uppercase tracking-widest">Our Recommendation</p>
          </div>
        </div>
        <h2 className="text-2xl sm:text-3xl font-extrabold mb-1">{winner.label}</h2>
        <p className="text-gray-300 text-sm mb-6 max-w-xl leading-relaxed">{winner.description}</p>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
          <div className="bg-white/10 rounded-xl p-3 backdrop-blur-sm">
            <p className="text-emerald-300 text-[10px] uppercase">Payoff</p>
            <p className="text-lg sm:text-xl font-bold">{ym(winner.payoffMonths)}</p>
            <p className="text-emerald-200 text-xs">{inputs.tenureYears * 12 - winner.payoffMonths > 0 ? `${Math.floor((inputs.tenureYears * 12 - winner.payoffMonths) / 12)}y faster` : "Full term"}</p>
          </div>
          <div className="bg-white/10 rounded-xl p-3 backdrop-blur-sm">
            <p className="text-emerald-300 text-[10px] uppercase">Interest Paid</p>
            <p className="text-lg sm:text-xl font-bold">{fmt(winner.totalInterest)}</p>
            {winner.interestSaved > 0 && <p className="text-emerald-200 text-xs">Save {fmt(winner.interestSaved)}</p>}
          </div>
          <div className="bg-white/10 rounded-xl p-3 backdrop-blur-sm">
            <p className="text-emerald-300 text-[10px] uppercase">Investment</p>
            <p className="text-lg sm:text-xl font-bold">{winner.investmentValue > 0 ? fmt(winner.investmentValue) : "—"}</p>
            <p className="text-gray-300 text-xs">{winner.totalInvested > 0 ? `From ${fmt(winner.totalInvested)}` : "All to loan"}</p>
          </div>
          <div className="bg-white/10 rounded-xl p-3 backdrop-blur-sm">
            <p className="text-emerald-300 text-[10px] uppercase">Net Worth</p>
            <p className="text-lg sm:text-xl font-bold">{fmt(winner.netWorth)}</p>
            <p className="text-gray-300 text-xs">Home + investments</p>
          </div>
        </div>

        <div className="bg-white/5 rounded-xl p-4 border border-white/10 space-y-2">
          <p className="text-sm leading-relaxed">
            With <span className="text-emerald-400 font-bold">{winner.label}</span>, you could
            {winner.interestSaved > 0 && <> save <span className="text-emerald-400 font-bold">{fmt(winner.interestSaved)}</span> in interest</>}
            {winner.interestSaved > 0 && winner.investmentValue > 0 && <> and</>}
            {winner.investmentValue > 0 && <> build <span className="text-blue-300 font-bold">{fmt(winner.investmentValue)}</span> in investments</>}
            {winner.interestSaved > 0 && winner.investmentValue > 0
              ? <> — that&apos;s <span className="text-amber-300 font-bold">{fmt(totalSaved)}</span> in total benefit.</>
              : <>.</>}
          </p>
          <p className="text-xs text-gray-400">
            After taxes &amp; LTCG: <span className="text-amber-300 font-semibold">{fmt(postTaxTotal)}</span> net benefit
            {winner.taxBreakdown.totalTaxSaved > 0 && <> · Tax saved: {fmt(winner.taxBreakdown.totalTaxSaved)}</>}
          </p>
        </div>
        <div className="mt-4 flex items-start gap-2.5 bg-white/5 rounded-xl p-3 border border-white/5">
          <span className="text-sm shrink-0 mt-0.5">💭</span>
          <div className="text-xs text-gray-400 leading-relaxed">
            <span className="text-gray-300 font-semibold">Beyond the numbers.</span>{' '}
            {winner.tag === "prepay"
              ? "Prepaying gives a guaranteed return equal to your loan rate and the peace of mind of being debt-free sooner. If that's worth more to you than the potential upside of investing, this is your path even if the gap is narrow."
              : winner.tag === "invest"
              ? "Investing has higher expected returns but comes with market risk. If the peace of mind of being debt-free matters more, prepaying could still be the right call even if the numbers say otherwise."
              : "The balanced path gives you some of both — a faster payoff and market exposure. It's the middle road if you can't decide."}
          </div>
        </div>
      </div>
    </motion.div>
  );
}

function TaxBreakdownCard({ paths, taxRate }: { paths: PathResult[]; taxRate: number }) {
  return (
    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}
      className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-7 h-7 rounded-lg bg-amber-50 flex items-center justify-center text-xs">📋</div>
        <h3 className="text-sm font-bold text-gray-900">Tax Impact</h3>
        <span className="text-xs text-gray-400">at {taxRate}% bracket</span>
      </div>
      <p className="text-xs text-gray-500 mb-4 leading-relaxed">
        Section 24 lets you deduct up to ₹2L/yr in home loan interest. Section 80C lets you deduct up to ₹1.5L/yr in principal repaid.
        Investment gains above ₹1L are taxed at 10% LTCG.
      </p>
      <div className="overflow-x-auto">
        <table className="w-full text-xs">
          <thead>
            <tr className="border-b border-gray-100">
              <th className="text-left py-2 pr-4 text-gray-500 font-semibold uppercase tracking-wider">Strategy</th>
              <th className="text-right py-2 px-3 text-gray-500 font-semibold uppercase tracking-wider">Sec 24 Saved</th>
              <th className="text-right py-2 px-3 text-gray-500 font-semibold uppercase tracking-wider">Sec 80C Saved</th>
              <th className="text-right py-2 px-3 text-gray-500 font-semibold uppercase tracking-wider">LTCG Tax</th>
              <th className="text-right py-2 pl-3 text-gray-500 font-semibold uppercase tracking-wider">Post-Tax Benefit</th>
            </tr>
          </thead>
          <tbody>
            {paths.map((p, i) => (
              <tr key={p.id} className={`${i === 0 ? "bg-emerald-50/50" : ""} border-b border-gray-50`}>
                <td className="py-2.5 pr-4">
                  <span className="mr-1.5">{p.emoji}</span>
                  <span className={`font-semibold ${i === 0 ? "text-emerald-700" : "text-gray-700"}`}>{p.label}</span>
                  {i === 0 && <span className="ml-1.5 text-[10px] bg-emerald-100 text-emerald-700 font-bold px-1.5 py-0.5 rounded">BEST</span>}
                </td>
                <td className="text-right py-2.5 px-3 font-medium text-gray-900">{fmt(p.taxBreakdown.section24Savings)}</td>
                <td className="text-right py-2.5 px-3 font-medium text-gray-900">{fmt(p.taxBreakdown.section80CSavings)}</td>
                <td className="text-right py-2.5 px-3 font-medium" style={{ color: p.taxBreakdown.ltcgTax > 0 ? "#dc2626" : "#94a3b8" }}>
                  {p.taxBreakdown.ltcgTax > 0 ? fmt(p.taxBreakdown.ltcgTax) : "—"}
                </td>
                <td className="text-right py-2.5 pl-3 font-bold text-gray-900">{fmt(p.totalBenefit)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </motion.div>
  );
}

function InflationCard({ paths, inflationRate }: { paths: PathResult[]; inflationRate: number }) {
  return (
    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
      className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-7 h-7 rounded-lg bg-rose-50 flex items-center justify-center text-xs">📉</div>
        <h3 className="text-sm font-bold text-gray-900">Inflation Reality Check</h3>
        <span className="text-xs text-gray-400">at {inflationRate}% inflation</span>
      </div>
      <p className="text-xs text-gray-500 mb-4 leading-relaxed">
        Inflation erodes the real value of money over time. ₹1Cr today will not buy the same in 20 years.
        Here&apos;s what each strategy&apos;s net worth is actually worth in <em>today&apos;s purchasing power</em>.
      </p>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        {paths.map((p, i) => (
          <div key={p.id} className={`rounded-xl p-4 ${i === 0 ? "bg-emerald-50 border border-emerald-200" : "bg-gray-50 border border-gray-100"}`}>
            <div className="flex items-center gap-1.5 mb-2">
              <span>{p.emoji}</span>
              <span className={`text-sm font-bold ${i === 0 ? "text-emerald-800" : "text-gray-700"}`}>{p.label}</span>
              {i === 0 && <span className="text-[10px] bg-emerald-100 text-emerald-700 font-bold px-1.5 py-0.5 rounded ml-auto">BEST</span>}
            </div>
            <div className="space-y-1">
              <div className="flex justify-between text-xs">
                <span className="text-gray-500">Nominal</span>
                <span className="font-semibold text-gray-900">{fmtShort(p.netWorth)}</span>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-gray-500">Inflation-adjusted</span>
                <span className="font-semibold text-rose-600">{fmtShort(p.netWorthReal)}</span>
              </div>
              <div className="flex justify-between text-xs pt-1 border-t border-gray-200">
                <span className="text-gray-500">Purchasing power loss</span>
                <span className="font-semibold text-rose-500">-{fmtShort(p.netWorth - p.netWorthReal)}</span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </motion.div>
  );
}

function WhatIfSection({ scenarios }: { scenarios: Evaluation["whatIfScenarios"] }) {
  const [activeIdx, setActiveIdx] = useState(1);
  const active = scenarios[activeIdx];
  if (!active) return null;

  return (
    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.25 }}
      className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-7 h-7 rounded-lg bg-purple-50 flex items-center justify-center text-xs">🔀</div>
        <h3 className="text-sm font-bold text-gray-900">What If Your Surplus Changes?</h3>
      </div>
      <div className="flex gap-2 mb-4">
        {scenarios.map((s, i) => (
          <button key={s.id} onClick={() => setActiveIdx(i)}
            className={`flex-1 py-2 px-3 rounded-xl text-xs font-semibold transition-all ${
              i === activeIdx
                ? "bg-gray-900 text-white shadow-md"
                : "bg-gray-50 text-gray-600 hover:bg-gray-100"
            }`}>
            {s.label}
            <span className="block text-[10px] opacity-70 mt-0.5">{s.multiplier}x surplus</span>
          </button>
        ))}
      </div>
      <div className="flex flex-wrap items-center gap-3 p-3 rounded-xl bg-gray-50">
        <span className="text-lg">{active.evaluation.winner.emoji}</span>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-bold text-gray-900">{active.evaluation.winner.label}</p>
          <p className="text-xs text-gray-500">{active.evaluation.winner.description}</p>
        </div>
        <div className="flex gap-4 text-xs">
          <div className="text-center">
            <p className="text-gray-500">Payoff</p>
            <p className="font-bold text-gray-900">{ym(active.evaluation.winner.payoffMonths)}</p>
          </div>
          <div className="text-center">
            <p className="text-gray-500">Benefit</p>
            <p className="font-bold text-emerald-600">{fmtShort(active.evaluation.winner.totalBenefit)}</p>
          </div>
          <div className="text-center">
            <p className="text-gray-500">Net Worth</p>
            <p className="font-bold text-gray-900">{fmtShort(active.evaluation.winner.netWorth)}</p>
          </div>
        </div>
      </div>
    </motion.div>
  );
}

function PathCard({ path, rank }: { path: PathResult; rank: number }) {
  const isWinner = rank === 0;
  const score = path.totalBenefit;
  const mScore = 5000000;
  return (
    <motion.div initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.08 * rank }}
      className={`rounded-2xl border-2 p-5 transition-all ${isWinner ? "border-emerald-300 bg-emerald-50/70 shadow-md" : "border-gray-100 bg-white hover:shadow-sm"}`}>
      <div className="flex items-start gap-3">
        <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold shrink-0 mt-0.5 ${isWinner ? "bg-emerald-500 text-white shadow-md shadow-emerald-200" : "bg-gray-100 text-gray-500"}`}>
          {isWinner ? "★" : rank + 1}
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2 mb-1">
            <span className="text-lg">{path.emoji}</span>
            <h4 className="font-bold text-gray-900">{path.label}</h4>
            {isWinner && <span className="text-[10px] bg-emerald-100 text-emerald-700 font-bold px-2 py-0.5 rounded-full">BEST</span>}
          </div>
          <p className="text-xs text-gray-500 mb-3">{path.description}</p>
          <div className="grid grid-cols-5 gap-2 text-center mb-3">
            <div>
              <p className="text-[10px] text-gray-500 uppercase">Payoff</p>
              <p className="text-sm font-bold text-gray-900">{ym(path.payoffMonths)}</p>
            </div>
            <div>
              <p className="text-[10px] text-gray-500 uppercase">Interest</p>
              <p className="text-sm font-bold text-gray-900">{fmt(path.totalInterest)}</p>
              {path.interestSaved > 0 && <p className="text-[10px] text-emerald-600">-{fmt(path.interestSaved)}</p>}
            </div>
            <div>
              <p className="text-[10px] text-gray-500 uppercase">Invest</p>
              <p className="text-sm font-bold text-gray-900">{path.investmentValue > 0 ? fmt(path.investmentValue) : "—"}</p>
              {path.taxBreakdown.ltcgTax > 0 && <p className="text-[10px] text-rose-500">-{fmt(path.taxBreakdown.ltcgTax)} tax</p>}
            </div>
            <div>
              <p className="text-[10px] text-gray-500 uppercase">Net Worth</p>
              <p className="text-sm font-bold text-gray-900">{fmt(path.netWorth)}</p>
              <p className="text-[10px] text-rose-500">{fmtShort(path.netWorthReal)} real</p>
            </div>
            <div>
              <p className="text-[10px] text-gray-500 uppercase">Monthly</p>
              <p className="text-sm font-bold text-gray-900">{fmt(path.monthlyCommitment)}</p>
            </div>
          </div>
          <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
            <motion.div initial={{ width: 0 }} animate={{ width: `${Math.min(100, (score / mScore) * 100)}%` }}
              transition={{ duration: 0.6, delay: 0.1 * rank }}
              className={`h-full rounded-full ${isWinner ? "bg-emerald-500" : "bg-blue-400"}`} />
          </div>
        </div>
      </div>
    </motion.div>
  );
}

export default function ResultsDashboard({ evaluation, onBack }: Props) {
  const { inputs, paths, winner, standardPayoffMonths, whatIfScenarios } = evaluation;
  const { handleExport, exporting, error: pdfError, clearError: clearPdfError } = usePdfExport(evaluation);

  const allChartData = paths.map(p => p.chartData);
  const maxYear = Math.max(...allChartData.flat().map(d => d.year));

  const mergedData = Array.from({ length: maxYear + 1 }, (_, y) => {
    const point: Record<string, number> = { year: y };
    paths.forEach((p) => {
      const d = p.chartData.find(c => c.year === y);
      point[`${p.label} (Balance)`] = d?.balance ?? 0;
      point[`${p.label} (Net Worth)`] = d?.netWorth ?? 0;
      point[`${p.label} (Real Worth)`] = d?.netWorthReal ?? 0;
    });
    return point;
  });

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <motion.button onClick={onBack} whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
          className="text-sm text-gray-500 hover:text-gray-900 transition-colors flex items-center gap-1">
          ← Back
        </motion.button>
        <div className="flex items-center gap-3">
          <div className="text-xs text-gray-500 bg-gray-50 px-3 py-1.5 rounded-full font-medium">
            ₹{(inputs.principal / 100000).toFixed(1)}L @ {inputs.annualRate}% · {inputs.expectedReturnRate}% return · {inputs.taxRate}% tax
          </div>
          <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
            onClick={() => { clearPdfError(); handleExport(); }} disabled={exporting}
            className="px-4 py-1.5 bg-gray-900 hover:bg-gray-800 disabled:bg-gray-400 text-white text-xs font-semibold rounded-xl transition-all flex items-center gap-1.5">
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
            {exporting ? "Exporting..." : "PDF Report"}
          </motion.button>
        </div>
      </div>
      {pdfError && (
        <div className="bg-red-50 border border-red-200 rounded-xl px-4 py-3 text-sm text-red-700 flex items-center gap-2">
          <span>⚠️</span>
          <span>{pdfError}</span>
          <button onClick={clearPdfError} className="ml-auto text-red-400 hover:text-red-600 font-bold">✕</button>
        </div>
      )}

      <div className="space-y-6">
        <VerdictCard winner={winner} inputs={inputs} />

        <TaxBreakdownCard paths={paths} taxRate={inputs.taxRate} />

        <InflationCard paths={paths} inflationRate={inputs.inflationRate} />

        <WhatIfSection scenarios={whatIfScenarios} />

        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
          <div className="flex items-center gap-2 mb-1">
            <div className="w-7 h-7 rounded-lg bg-blue-50 flex items-center justify-center text-xs">📈</div>
            <h3 className="text-sm font-bold text-gray-900">Balance &amp; Net Worth Over Time</h3>
          </div>
          <p className="text-xs text-gray-500 mb-4">Solid lines = loan balance · Dashed lines = net worth (nominal) · Dotted = inflation-adjusted</p>
          <ResponsiveContainer width="100%" height={260}>
            <LineChart data={mergedData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis dataKey="year" tick={{ fontSize: 11, fill: "#94a3b8" }} />
              <YAxis tick={{ fontSize: 11, fill: "#94a3b8" }} tickFormatter={toLakhs} />
              <Tooltip formatter={(v) => [fmt(Number(v) || 0), undefined]} labelFormatter={(l) => `Year ${l}`} />
              <Legend wrapperStyle={{ fontSize: "10px" }} />
              {paths.map(p => (
                <Line key={`${p.id}-bal`} type="monotone" dataKey={`${p.label} (Balance)`} stroke={colors[p.tag]} strokeWidth={2} dot={false} name={`${p.emoji} ${p.label}`} />
              ))}
              {paths.map(p => (
                <Line key={`${p.id}-nw`} type="monotone" dataKey={`${p.label} (Net Worth)`} stroke={colors[p.tag]} strokeWidth={1.5} strokeDasharray="5 4" dot={false} name={`${p.emoji} ${p.label} (NW)`} />
              ))}
              {paths.map(p => (
                <Line key={`${p.id}-real`} type="monotone" dataKey={`${p.label} (Real Worth)`} stroke={colors[p.tag]} strokeWidth={1} strokeDasharray="2 3" dot={false} name={`${p.emoji} ${p.label} (Real)`} opacity={0.5} />
              ))}
            </LineChart>
          </ResponsiveContainer>
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-bold text-gray-900">Compare Your Options</h3>
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-xs">
                <thead>
                  <tr className="border-b border-gray-100 bg-gray-50/50">
                    <th className="text-left py-3 px-4 text-gray-500 font-semibold uppercase tracking-wider">Path</th>
                    <th className="text-center py-3 px-3 text-gray-500 font-semibold uppercase tracking-wider">Payoff</th>
                    <th className="text-center py-3 px-3 text-gray-500 font-semibold uppercase tracking-wider">Interest Paid</th>
                    <th className="text-center py-3 px-3 text-gray-500 font-semibold uppercase tracking-wider">You Save</th>
                    <th className="text-center py-3 px-3 text-gray-500 font-semibold uppercase tracking-wider">You Earn</th>
                    <th className="text-center py-3 px-3 text-gray-500 font-semibold uppercase tracking-wider">Post-Tax</th>
                    <th className="text-center py-3 px-3 text-gray-500 font-semibold uppercase tracking-wider">Net Worth</th>
                    <th className="text-center py-3 pl-3 pr-4 text-gray-500 font-semibold uppercase tracking-wider">Real Worth</th>
                  </tr>
                </thead>
                <tbody>
                  {paths.map((p, i) => (
                    <tr key={p.id} className={`${i === 0 ? "bg-emerald-50/50" : ""} border-b border-gray-50`}>
                      <td className="py-3 px-4">
                        <div className="flex items-center gap-2">
                          <span>{p.emoji}</span>
                          <span className={`font-semibold text-sm ${i === 0 ? "text-gray-900" : "text-gray-700"}`}>{p.label}</span>
                          {i === 0 && <span className="text-[10px] bg-emerald-100 text-emerald-700 font-bold px-1.5 py-0.5 rounded">BEST</span>}
                        </div>
                      </td>
                      <td className="text-center py-3 px-3">
                        <span className="font-bold text-gray-900 text-sm">{ym(p.payoffMonths)}</span>
                        {p.payoffMonths < standardPayoffMonths && (
                          <p className="text-[10px] text-emerald-600">{Math.floor((standardPayoffMonths - p.payoffMonths) / 12)}y early</p>
                        )}
                      </td>
                      <td className="text-center py-3 px-3 font-bold text-sm text-gray-900">{fmtIntrinsic(p.totalInterest)}</td>
                      <td className="text-center py-3 px-3 font-bold text-sm" style={{ color: p.interestSaved > 0 ? "#059669" : "#94a3b8" }}>
                        {p.interestSaved > 0 ? fmtIntrinsic(p.interestSaved) : "—"}
                      </td>
                      <td className="text-center py-3 px-3 font-bold text-sm" style={{ color: p.investmentValue > 0 ? "#2563eb" : "#94a3b8" }}>
                        {p.investmentValue > 0 ? fmtIntrinsic(p.investmentValue) : "—"}
                      </td>
                      <td className="text-center py-3 px-3 font-bold text-sm text-gray-900">{fmtIntrinsic(p.totalBenefit)}</td>
                      <td className="text-center py-3 px-3 font-bold text-sm text-gray-900">{fmtIntrinsic(p.netWorth)}</td>
                      <td className="text-center py-3 pl-3 pr-4 font-bold text-sm text-rose-600">{fmtIntrinsic(p.netWorthReal)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div className="grid gap-3">
          <h3 className="text-base font-bold text-gray-900">Detailed Breakdown</h3>
          {paths.map((p, i) => <PathCard key={p.id} path={p} rank={i} />)}
        </div>
      </div>

      <div className="flex gap-3 justify-center pt-2 pb-8">
        <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
          onClick={onBack}
          className="px-6 py-3 bg-gray-100 hover:bg-gray-200 text-gray-900 font-medium rounded-xl text-sm transition-all">
          ← Try Different Numbers
        </motion.button>
        <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
          onClick={() => { clearPdfError(); handleExport(); }} disabled={exporting}
          className="px-6 py-3 bg-gray-900 hover:bg-gray-800 disabled:bg-gray-400 text-white font-medium rounded-xl text-sm transition-all flex items-center gap-2">
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
          {exporting ? "Exporting..." : "Download PDF Report"}
        </motion.button>
      </div>
    </div>
  );
}

function fmtIntrinsic(n: number) {
  if (Math.abs(n) >= 10000000) return `₹${(n / 10000000).toFixed(1)}Cr`;
  if (Math.abs(n) >= 100000) return `₹${(n / 100000).toFixed(1)}L`;
  return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);
}
